services:

  mongo_dev:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER:-ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD:-1234}
    networks:
      - telware_dev_net
    volumes:
      - mongo_dev_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', "db.adminCommand('ping')"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 45s

  backend_dev:
    image: telware/telware-backend:latest_dev
    ports:
      - '${PORT:-3001}:3000'
    restart: always
    depends_on:
      mongo_dev:
        condition: service_healthy
      redis_dev:
        condition: service_healthy
    networks:
      - telware_dev_net

  redis_dev:
    image: redis/redis-stack
    restart: unless-stopped
    networks:
      - telware_dev_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20m
      timeout: 5s
      retries: 5
      start_period: 45s

  frontend_dev:
    image: telware/telware-frontend:latest_dev
    ports:
      - 8082:5174
    restart: always
    depends_on:
      - backend_dev
    
  
networks:
  telware_dev_net:

volumes:
  mongo_dev_data:
