services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER:-ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD:-1234}
    networks:
      - telware_net
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', "db.adminCommand('ping')"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 45s

  backend:
    image: telware/telware-backend:latest
    ports:
      - '${PORT:-3000}:3000'
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - telware_net

  redis:
    image: redis/redis-stack
    restart: unless-stopped
    networks:
      - telware_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20m
      timeout: 5s
      retries: 5
      start_period: 45s

  frontend:
    image: telware/telware-frontend:latest
    ports:
      - 8081:80
    restart: always
    depends_on:
      - backend
    

networks:
  telware_net:

volumes:
  mongo-data:
